[package]
name = "octosense-reference"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
makepad-widgets = { git = "https://github.com/OctoSense-org/makepad.git", rev = "3c82c18f42baa8e4a20d1efe4e42d07df1197669" }
makepad-app-module = { git = "https://github.com/OctoSense-org/makepad.git", rev = "3c82c18f42baa8e4a20d1efe4e42d07df1197669" }
