[package]
name = "octosense-photos"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
makepad-widgets = { git = "https://github.com/OctoSense-org/makepad.git", rev = "e7c1cdf6ca0bbb22cd8692408567cb93cf6928a4", features = ["appcard"] }
makepad-app-module = { git = "https://github.com/OctoSense-org/makepad.git", rev = "e7c1cdf6ca0bbb22cd8692408567cb93cf6928a4" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
