#!/usr/bin/env python3
"""Build the Home/Bridge APK pair for ordinary Android or OctoSense ROM."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def arguments(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--variant", required=True, choices=("standalone", "rom"))
    p.add_argument("--sdk", required=True, type=Path, help="Prepared cargo-makepad Android SDK/NDK/JDK directory")
    p.add_argument("--android-sdk", required=True, type=Path, help="Android SDK with platform 35 and build-tools 35.0.0")
    p.add_argument("--gradle-home", type=Path, help="Installed Gradle 8.11.1 distribution (or use PATH)")
    p.add_argument("--java-home", type=Path, default=os.environ.get("JAVA_HOME"), help="Full installed JDK 17+ for Gradle; defaults to JAVA_HOME")
    p.add_argument("--packager", type=Path, help="Use an already built cargo-makepad; otherwise build the pinned source")
    p.add_argument("--sign-key", type=Path, help="Existing signer PKCS#8 key; never generated by this command")
    p.add_argument("--sign-cert", type=Path, help="Existing signer X.509 certificate")
    p.add_argument("--development", action="store_true", help="Standalone only: sign both APKs with Makepad's development keystore")
    p.add_argument("--version-code", default="auto")
    p.add_argument("--output", type=Path)
    p.add_argument("--offline", action="store_true")
    p.add_argument("--dry-run", action="store_true", help="Print the build plan without executing or signing")
    args = p.parse_args(argv)
    if bool(args.sign_key) != bool(args.sign_cert):
        p.error("--sign-key and --sign-cert must be supplied together")
    if args.development and (args.variant != "standalone" or args.sign_key):
        p.error("--development is only for standalone builds without release keys")
    if not args.development and not args.sign_key:
        p.error("Supply the existing signer with --sign-key/--sign-cert, or use --development for standalone testing")
    if args.version_code != "auto" and (not args.version_code.isdigit() or not 0 < int(args.version_code) < 2100000000):
        p.error("--version-code must be auto or a positive Android version code")
    for name in ("sdk", "android_sdk", "gradle_home", "java_home", "packager", "sign_key", "sign_cert", "output"):
        if getattr(args, name):
            setattr(args, name, Path(getattr(args, name)).resolve())
    args.java_home = args.java_home or args.sdk / "openjdk"
    args.output = args.output or ROOT / "out/home" / args.variant
    return args


def build_plan(args):
    sources = ROOT / ".sources"
    cargo = ["cargo", "build", "--locked", "--release", "--manifest-path", str(sources / "makepad/tools/cargo_makepad/Cargo.toml")]
    gradle = [str(ROOT / "home/android/gradlew"), "--no-daemon", ":contracts:exportHomeContracts", ":system-bridge:assembleRelease"]
    packager = args.packager or sources / "makepad/target/release/cargo-makepad"
    android = [str(packager), "makepad", "android", f"--sdk-path={args.sdk}", "--abi=aarch64", f"--version-code={args.version_code}", "--no-sign", "build", "-p", "octosense", "--release", "--locked"]
    if args.offline:
        cargo.append("--offline")
        gradle.append("--offline")
        android.append("--offline")
    plan = [(ROOT, [sys.executable, str(ROOT / "scripts/setup-home.py"), "--check"])]
    if not args.packager:
        plan.append((sources / "makepad", cargo))
    return plan + [(ROOT / "home/android", gradle), (ROOT / "home", android)]


def certificate_digest(apksigner, apk, env):
    output = subprocess.check_output([str(apksigner), "verify", "--print-certs", str(apk)], env=env, text=True)
    match = re.search(r"Signer #1 certificate SHA-256 digest: ([0-9a-f]+)", output)
    if not match:
        raise RuntimeError(f"No verified signing certificate for {apk.name}")
    return match[1]


def main(argv=None):
    args = arguments(argv)
    plan = build_plan(args)
    if args.dry_run:
        print(json.dumps({"variant": args.variant, "development": args.development,
                          "output": str(args.output), "steps": [
                              {"cwd": str(cwd), "argv": command} for cwd, command in plan],
                          "artifacts": ["OctoSenseHome.apk", "OctoSenseBridge.apk", "build.json"],
                          "installs_or_flashes": False}, indent=2))
        return
    sources = ROOT / ".sources"
    for path in (args.java_home / "bin/java", args.android_sdk / "platforms/android-35/android.jar",
                 args.android_sdk / "build-tools/35.0.0/apksigner"):
        if not path.is_file():
            raise RuntimeError(f"Required Android tool missing: {path}")
    if args.sign_key:
        for path in (args.sign_key, args.sign_cert):
            if not path.is_file():
                raise RuntimeError(f"Signing input does not exist: {path}")
            if path.is_relative_to(ROOT):
                raise RuntimeError("Keep signing keys and certificates outside the product checkout")
    env = dict(os.environ)
    env.update(JAVA_HOME=str(args.java_home), ANDROID_HOME=str(args.android_sdk),
               ANDROID_SDK_ROOT=str(args.android_sdk), OCTOSENSE_WORKSPACE=str(sources))
    env["PATH"] = str(args.java_home / "bin") + os.pathsep + env.get("PATH", "")
    # Always build the unsigned Bridge release and sign the pair together below.
    env.pop("OCTOSENSE_KEYSTORE", None)
    env.pop("CARGO_TARGET_DIR", None)
    if args.gradle_home:
        env["OCTOSENSE_GRADLE_HOME"] = str(args.gradle_home)
    env["RUSTFLAGS"] = (env.get("RUSTFLAGS", "") + f" --remap-path-prefix={ROOT}=/octosense-rom --remap-path-prefix={Path.home()}=/build").strip()
    for cwd, command in plan:
        subprocess.run(command, cwd=cwd, env=env, check=True)
    inputs = {
        "OctoSenseHome.apk": ROOT / "home/target/android/makepad-android-apk/octosense/apk/octo_sense.apk",
        "OctoSenseBridge.apk": ROOT / "home/android/system-bridge/build/outputs/apk/release/system-bridge-release-unsigned.apk",
    }
    args.output.mkdir(parents=True, exist_ok=True)
    apksigner = args.android_sdk / "build-tools/35.0.0/apksigner"
    artifacts = {}
    for name, source in inputs.items():
        destination = args.output / name
        temporary = destination.with_suffix(".pending.apk")
        command = [str(apksigner), "sign"]
        if args.development:
            command += ["--ks", str(sources / "makepad/tools/cargo_makepad/debug.keystore"),
                        "--ks-key-alias", "androiddebugkey", "--ks-pass", "pass:android", "--key-pass", "pass:android"]
        else:
            command += ["--key", str(args.sign_key), "--cert", str(args.sign_cert)]
        subprocess.run(command + ["--out", str(temporary), str(source)], env=env, check=True)
        digest = certificate_digest(apksigner, temporary, env)
        temporary.replace(destination)
        artifacts[name] = {"sha256": hashlib.sha256(destination.read_bytes()).hexdigest(), "certificate_sha256": digest}
    if len({item["certificate_sha256"] for item in artifacts.values()}) != 1:
        raise RuntimeError("Home and Bridge must have the same signing identity")
    aapt = args.android_sdk / "build-tools/35.0.0/aapt2"
    badging = subprocess.check_output([str(aapt), "dump", "badging", str(args.output / "OctoSenseHome.apk")], env=env, text=True)
    version = re.search(r"versionCode='([0-9]+)'", badging).group(1)
    receipt = {"schema_version": 1, "variant": args.variant, "development": args.development,
               "home_version_code": int(version),
               "source_revision": subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip(),
               "source_dirty": bool(subprocess.check_output(["git", "-C", str(ROOT), "status", "--porcelain"], text=True)),
               "runtime": json.loads((ROOT / "home/native-runtime.lock.json").read_text()),
               "runtime_patches": json.loads((ROOT / "home/runtime-patches.lock.json").read_text()),
               "packager": str(args.packager) if args.packager else "pinned source",
               "native_apps": json.loads((ROOT / "home/native-apps.lock.json").read_text()),
               "artifacts": artifacts}
    (args.output / "build.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(f"Built {args.variant} Home {version} and Bridge in {args.output}")


if __name__ == "__main__":
    main()
